# Generated by Django 3.0 on 2020-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dentalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherNext3Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20, null=True)),
                ('specilization', models.CharField(max_length=30, null=True)),
                ('rating', models.FloatField(null=True)),
                ('fee', models.FloatField(null=True)),
                ('distance', models.CharField(max_length=50, null=True)),
                ('avilable_in', models.CharField(max_length=100, null=True)),
                ('doctor', models.ImageField(null=True, upload_to='doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='Next3Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20, null=True)),
                ('specilization', models.CharField(max_length=30, null=True)),
                ('rating', models.FloatField(null=True)),
                ('fee', models.FloatField(null=True)),
                ('distance', models.CharField(max_length=50, null=True)),
                ('avilable_in', models.CharField(max_length=100, null=True)),
                ('doctor', models.ImageField(null=True, upload_to='doctors/')),
            ],
        ),
    ]
